//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JollyPoker.UI.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JollyPoker.UI.Templates.CardTemplates", typeof(CardTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒
        ///▒▒▒▒▒▒▒▒▒▒▒.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  A         
        ///           
        ///           
        ///           
        ///     $     
        ///           
        ///           
        ///           
        ///         A .
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10         
        ///  $     $  
        ///     $     
        ///  $     $  
        ///           
        ///  $     $  
        ///     $     
        ///  $     $  
        ///         10.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  J         
        ///  $        
        ///           
        ///           
        ///           
        ///           
        ///           
        ///        $  
        ///         J .
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Q         
        ///  $        
        ///           
        ///           
        ///           
        ///           
        ///           
        ///        $  
        ///         Q .
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  K         
        ///  $        
        ///           
        ///           
        ///           
        ///           
        ///           
        ///        $  
        ///         K .
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  J         
        /// O         
        /// K         
        /// E         
        /// R       R 
        ///         E 
        ///         K 
        ///         O 
        ///         J .
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  2         
        ///     $     
        ///           
        ///           
        ///           
        ///           
        ///           
        ///     $     
        ///         2 .
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  3         
        ///     $     
        ///           
        ///           
        ///     $     
        ///           
        ///           
        ///     $     
        ///         3 .
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  4         
        ///  $     $  
        ///           
        ///           
        ///           
        ///           
        ///           
        ///  $     $  
        ///         4 .
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  5         
        ///  $     $  
        ///           
        ///           
        ///     $     
        ///           
        ///           
        ///  $     $  
        ///         5 .
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  6         
        ///  $     $  
        ///           
        ///           
        ///  $     $  
        ///           
        ///           
        ///  $     $  
        ///         6 .
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  7         
        ///  $     $  
        ///     $     
        ///           
        ///  $     $  
        ///           
        ///           
        ///  $     $  
        ///         7 .
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8         
        ///  $     $  
        ///     $     
        ///           
        ///  $     $  
        ///           
        ///     $     
        ///  $     $  
        ///         8 .
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  9         
        ///  $     $  
        ///           
        ///  $     $  
        ///     $     
        ///  $     $  
        ///           
        ///  $     $  
        ///         9 .
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
    }
}
